
- id: "rs-${dir}"
  desc: "Rawseeds dataset ${dir}"
  code: 
  - rawlogs.library.Multiple
  - annotations: {}
    logs:
    - - dataset_rawseeds.RawseedsOdometry
      - "file:filename": "${dir}/ODOMETRY_XYT.csv.bz2"
    - - dataset_rawseeds.RawseedsHokuyo
      - "file:filename": "${dir}/HOKUYO_FRONT.csv.bz2"
        signal_name: 'hokuyo_front'
    - - dataset_rawseeds.RawseedsHokuyo
      - "file:filename": "${dir}/HOKUYO_REAR.csv.bz2"
        signal_name: 'hokuyo_rear'
    - - dataset_rawseeds.RawseedsRF
      - "file:filename": "${dir}/SICK_FRONT.csv.bz2"
        signal_name: 'sick_front'
    - - dataset_rawseeds.RawseedsRF
      - "file:filename": "${dir}/SICK_REAR.csv.bz2"
        signal_name: 'sick_rear'
    - - dataset_rawseeds.RawseedsIMU
      - "file:filename": "${dir}/IMU_STRETCHED.csv.bz2"
    - - procgraph_rawlogs.VideoLog
      - "file:filename": "${dir}/OMNI.avi"
        signal_name: omni
    - - procgraph_rawlogs.VideoLog
      - "file:filename": "${dir}/FRONTAL.avi"
        signal_name: frontal
    - - procgraph_rawlogs.VideoLog
      - "file:filename": "${dir}/SVS_L.avi"
        signal_name: svs_l
    - - procgraph_rawlogs.VideoLog
      - "file:filename": "${dir}/SVS_R.avi"
        signal_name: svs_r
    - - procgraph_rawlogs.VideoLog
      - "file:filename": "${dir}/SVS_T.avi"
        signal_name: svs_t

- id: "rsf-${dir}"
  desc: "Filtered rawseeds dataset ${dir}"
  code: 
  - rawlogs.library.RemoveSignals
  - signals: 
    - acceleration
    - x
    - y
    - theta
    - rolling_counter
    - counter
    - angular_velocity
    - magnetic_field
    - attitude
    - ticks_right
    - ticks_left
    - pose
    - pose_SE2
    rawlog:
    - rawlogs_filters.ProcgraphFilter
    - rawlog: "rs-${dir}"
      model: [procgraph_robotics.vel_from_SE2_seq, {}]
      inputs: 
        pose_SE2: pose
      outputs:
        velocity: velocity




- id: rs-Bicocca_2009-02-25a
- id: rs-Bicocca_2009-02-25b
- id: rs-Bicocca_2009-02-26a
- id: rs-Bicocca_2009-02-26b
- id: rs-Bicocca_2009-02-27a
- id: rs-Bovisa_2008-09-01
- id: rs-Bovisa_2008-10-04
- id: rs-Bovisa_2008-10-06
- id: rs-Bovisa_2008-10-07
- id: rs-Bovisa_2008-10-11a
- id: rs-Bovisa_2008-10-11b

